// import 'package:application5/controller/cont/PaymentMethodController.dart';
// import 'package:application5/controller/cont/cart_controller.dart';
// import 'package:application5/controller/cont/orders_controller.dart';
// import 'package:application5/model/order_model.dart';
// import 'package:application5/pages/2orders.dart';
// import 'package:flutter/material.dart';
// import 'package:get/get.dart';


// class CheckoutPage extends StatelessWidget {
//   final OrdersController ordersController = Get.find();
//   final PaymentMethodController paymentMethodController = Get.find();
//   final CartController cartController = Get.find();

//   final buildingNumberController = TextEditingController();
//   final apartmentNoController = TextEditingController();
//   final floorNoController = TextEditingController();
//   final streetNameController = TextEditingController();
//   final phoneNoController = TextEditingController();
//   final additionalDirectionsController = TextEditingController();

//   final formKey = GlobalKey<FormState>();

//   void submitCheckout() async {
//     if (formKey.currentState?.validate() == true) {
//       // Collect data from form fields
//       final buildingNumber = buildingNumberController.text;
//       final apartmentNo = apartmentNoController.text;
//       final floorNo = floorNoController.text;
//       final streetName = streetNameController.text;
//       final phoneNo = phoneNoController.text;
//       final additionalDirections = additionalDirectionsController.text;
//       final paymentMethod = paymentMethodController.paymentMethod.value;
      
//       // Calculate the total price of the order
//       final totalPrice = cartController.totalPrice;

//       // Create a new order
//       final order = Order(
//         orderId: '', // Order ID will be generated by Firestore
//         userId: 'currentUser', // Replace with your user ID logic
//         buildingNumber: buildingNumber,
//         apartmentNo: apartmentNo,
//         floorNo: floorNo,
//         streetName: streetName,
//         phoneNo: phoneNo,
//         additionalDirections: additionalDirections,
//         paymentMethod: paymentMethod,
//         status: 'Ongoing',
//         items: cartController.cartItems.toList(),
//         totalPrice: totalPrice,
//       );

//       // Save the order
//       await ordersController.saveOrder(order);

//       // Clear cart
//       cartController.cartItems.clear();

//       // Navigate to the MyOrdersPage
//       Get.to(MyOrdersPage());
//     }
//   }

//   @override
//   Widget build(BuildContext context) {
//     return Scaffold(
//       appBar: AppBar(
//         title: Text('Checkout'),
//       ),
//       body: Form(
//         key: formKey,
//         child: SingleChildScrollView(
//           padding: EdgeInsets.all(16.0),
//           child: Column(
//             children: [
//               TextFormField(
//                 controller: buildingNumberController,
//                 decoration: InputDecoration(labelText: 'Building Number'),
//                 validator: (value) {
//                   if (value?.isEmpty ?? true) {
//                     return 'Please enter your building number';
//                   }
//                   return null;
//                 },
//               ),
//               TextFormField(
//                 controller: apartmentNoController,
//                 decoration: InputDecoration(labelText: 'Apartment No'),
//                 validator: (value) {
//                   if (value?.isEmpty ?? true) {
//                     return 'Please enter your apartment number';
//                   }
//                   return null;
//                 },
//               ),
//               TextFormField(
//                 controller: floorNoController,
//                 decoration: InputDecoration(labelText: 'Floor No'),
//                 validator: (value) {
//                   if (value?.isEmpty ?? true) {
//                     return 'Please enter your floor number';
//                   }
//                   return null;
//                 },
//               ),
//               TextFormField(
//                 controller: streetNameController,
//                 decoration: InputDecoration(labelText: 'Street Name'),
//                 validator: (value) {
//                   if (value?.isEmpty ?? true) {
//                     return 'Please enter your street name';
//                   }
//                   return null;
//                 },
//               ),
//               TextFormField(
//                 controller: phoneNoController,
//                 decoration: InputDecoration(labelText: 'Phone No'),
//                 validator: (value) {
//                   if (value?.isEmpty ?? true) {
//                     return 'Please enter your phone number';
//                   }
//                   return null;
//                 },
//               ),
//               TextFormField(
//                 controller: additionalDirectionsController,
//                 decoration: InputDecoration(labelText: 'Additional Directions (optional)'),
//               ),
//               SizedBox(height: 20),
//               ElevatedButton(
//                 onPressed: submitCheckout,
//                 child: Text('Submit Checkout'),
//               ),
//             ],
//           ),
//         ),
//       ),
//     );
//   }
// }
